### ISSUE TITLE
Library not working on RN 0.61

### ISSUE THREAD

**Issue by mikaoelitiana** [Accengage/accengage-mobile-react-native#23]
I upgraded my project to RN O.61 and got the following error from react-native-acc module: 

```
In file included from /project_path/node_modules/react-native-acc/ios/RNAcc/RNAccStates.h:11:
../../react-native/React/Base/RCTBridgeModule.h:10:9: fatal error: 'React/RCTDefines.h' file not found
#import <React/RCTDefines.h>
```

**Comment by Apekka** [comment]
Bonjour Mikael, on est actuellement en train de travailler sur la mise à jour de notre plugin afin d'être compatible React Native 0.60+
Votre message d'erreur ressemble beaucoup à un souci d'Autolinking, on ne peut pas confirmer à 100% que c'est lié à ça, mais dès que notre plugin sera à jour on pourra investiguer plus profondément la source de l'erreur.

**Comment by mikaoelitiana** [comment]
Thanks @Apekka

**Comment by mikaoelitiana** [comment]
This is now fixed
